Added a safeguard for username when the owner is an unregistered user
orbit-love/community-js-stackoverflow-orbit pull request #17
Opened 2022-03-16 23:07 UTC by sindbach

This is a PR for https://github.com/orbit-love/community-js-stackoverflow-orbit/issues/16

Essentially this update is to use `question.owner.display_name` value if `question.owner.link` is undefined. 
The link can be undefined when a user is not a registered user (do not have a user profile link) for example: https://stackoverflow.com/questions/71464785/error-serializing-meetups0-title-returned-from-getstaticprops-in

In this case, the display name would be `user<numbers>` this would also be equal to the username

2022-03-24 23:53 UTC, mxdavis requested changes
Thanks for taking the time to submit a fix!

Looks pretty straightforward. 

Would you be interested in writing a  test for the unregistered user? I can try to see if I can add it next week.

2022-03-24 23:53 UTC, mxdavis commented on src/questions.js
> +                    let username = question.owner.display_name;
Should we use a ternary here?

2022-03-25 03:32 UTC, sindbach commented on src/questions.js
> +                    let username = question.owner.display_name;
Updated

2022-03-25 03:32 UTC, sindbach commented
@mxdavis, added a test for username values.

2022-03-28 15:14 UTC, merged